## 1. Introduction
<p>Everyone loves Lego (unless you ever stepped on one). Did you know by the way that "Lego" was derived from the Danish phrase leg godt, which means "play well"? Unless you speak Danish, probably not. </p>
<p>In this project, we will analyze a fascinating dataset on every single Lego block that has ever been built!</p>
<p><img src="https://s3.amazonaws.com/assets.datacamp.com/production/project_10/datasets/lego-bricks.jpeg" alt="lego"></p>

In [ ]:
# Nothing to do here

## 2. Reading Data
<p>A comprehensive database of lego blocks is provided by <a href="https://rebrickable.com/downloads/">Rebrickable</a>. The data is available as csv files and the schema is shown below.</p>
<p><img src="https://s3.amazonaws.com/assets.datacamp.com/production/project_10/datasets/downloads_schema.png" alt="schema"></p>
<p>Let us start by reading in the colors data to get a sense of the diversity of Lego sets!</p>

In [ ]:
# Import pandas
import pandas as pd

# Read colors data
colors = pd.read_csv('datasets/colors.csv')
colors.head()

# Print the first few rows

   id            name     rgb is_trans
0  -1         Unknown  0033B2        f
1   0           Black  05131D        f
2   1            Blue  0055BF        f
3   2           Green  237841        f
4   3  Dark Turquoise  008F9B        f

## 3. Exploring Colors
<p>Now that we have read the <code>colors</code> data, we can start exploring it! Let us start by understanding the number of colors available.</p>

In [ ]:
# How many distinct colors are available?
num_colors = (len(colors))

# Print num_colors
print(num_colors)

135

## 4. Transparent Colors in Lego Sets
<p>The <code>colors</code> data has a column named <code>is_trans</code> that indicates whether a color is transparent or not. It would be interesting to explore the distribution of transparent vs. non-transparent colors.</p>

In [ ]:
# colors_summary: Distribution of colors based on transparency
trans_group =colors.groupby('is_trans')
colors_summary = trans_group[['id', 'name', 'rgb']].count()
colors_summary

           id  name  rgb
is_trans
f         107   107  107
t          28    28   28

## 5. Explore Lego Sets
<p>Another interesting dataset available in this database is the <code>sets</code> data. It contains a comprehensive list of sets over the years and the number of parts that each of these sets contained. </p>
<p><img src="https://imgur.com/1k4PoXs.png" alt="sets_data"></p>
<p>Let us use this data to explore how the average number of parts in Lego sets has varied over the years.</p>

In [ ]:
%matplotlib inline
sets = pd.read_csv('datasets/sets.csv')


# Create a summary of average number of parts by year: `parts_by_year`
year_group = sets.groupby('year')
parts_by_year = round( year_group['num_parts'].mean(), 2)

# Plot trends in average number of parts by year

## 6. Lego Themes Over Years
<p>Lego blocks ship under multiple <a href="https://shop.lego.com/en-US/Themes">themes</a>. Let us try to get a sense of how the number of themes shipped has varied over the years.</p>

In [ ]:
# themes_by_year: Number of themes shipped by year
setyear_group = sets.groupby('year')
test = setyear_group['theme_id'].nunique()
themes_by_year = pd.DataFrame({'year': test.index, 'theme_id':test.values})
themes_by_year

    year  theme_id
0   1950         2
1   1953         1
2   1954         2
3   1955         4
4   1956         3
..   ...       ...
61  2013        93
62  2014        92
63  2015        99
64  2016        88
65  2017        78

[66 rows x 2 columns]

## 7. Wrapping It All Up!
<p>Lego blocks offer an unlimited amount of fun across ages. We explored some interesting trends around colors, parts, and themes. Before we wrap up, let's take a closer look at the <code>themes_by_year</code> DataFrame you created in the previous step.</p>

In [ ]:
# Get the number of unique themes released in 1999


# Print the number of unique themes released in 1999